name: app_auditoria_financiera
description: "App de Auditoría y Ahorro Financiero Familiar en Tiempo Real con Firebase Firestore y Almacenamiento Gratuito."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core & Base de Datos en Tiempo Real
  firebase_core: ^4.14.0
  cloud_firestore: ^6.9.0

  # Red & Subida gratuita a la nube
  http: ^1.2.2

  # Selección y compresión de imágenes
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1

  # Autenticación y Seguridad
  local_auth: ^2.3.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.6

  # Utilidades & Formato
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  
  # Iconos & UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
